### ISSUE TITLE
different values for  'mem_mb' and '--Xmx' NOT allowed

### ISSUE THREAD

**Issue by bguo068** [snakemake/snakemake-wrapper-utils#9]
Sometimes, it would be nice to have `mem_mb` value larger than `--Xmx` value. For example:

[From GATK `GenomicsDBImport` documentation:](https://gatk.broadinstitute.org/hc/en-us/articles/360036883491-GenomicsDBImport)
>IMPORTANT: The -Xmx value the tool is run with should be less than the total amount of physical memory available by at least a few GB, as the native TileDB library requires additional memory on top of the Java memory. Failure to leave enough memory for the native code can result in confusing error messages!

Can we add some logic in the `java.py` so that when the `mem_mb` value (15000MB) is larger than the `--Xmx` value (10000MB), snakemake will try to get more memory from the system and allow GenomicsDBImport (10000MB) and TileDb (5000MB) work together?

**Comment by dlaehnemann** [comment]
I just ran into the same issue, running the `picard MarkDuplicates` wrapper on a Slurm cluster. The `mem_mb` value is used for the resource request to the Slurm cluster and the `--Xmx` value in the `picard` command. This means that `picard` uses all of the specified `mem_mb` value for heap memory, but also uses some non-heap memory (like the TileDB stuff mentioned for GATK; for general info on non-heap memory allocation by the java virtual machine (JVM), there is a lot of stuff on stackoverflow, for example [this answer](https://stackoverflow.com/a/44610902)). As a result, the total memory used exceeds `mem_mb` and jobs get killed by the Slurm cluster.

I see several possible solutions:

1. We can just subtract a blanket percentage (e.g. 30%) from the `mem_mb` specification for the value that is passed to `--Xmx`. This will probably work for many java applications, but more extreme cases would not be covered. A lower percentage would mean that less memory is wasted for applications that have little (relative) overhead. A higher percentage would mean that more applications work out of the box with the standard `get_java_opts()` function.
2. Allow for the specification of the necessary overhead, for example via a `params: java_mem_overhead_mb=` field. This has the advantage of being more configurable and thus more precise, but it always requires the `java_mem_overhead_mb` parameter to be specified. In the example above, this would mean that we specifiy:
    * `mem_mb=15000`
    * `params: java_mem_overhead_mb=5000`
3. So maybe we should opt for a combination of both. We do a blanket 20% subtraction from `mem_mb` to `--Xmx`, unless `params: java_mem_overhead_mb=` exists. This way it will often work out of the box, but only reduce available heap space by 20%. And wherever that doesn't work, you just have to handle it manually by specifying the overhead. And the latter should probably be suggested via some stderr output from the wrapper and thus written into the `log:` file.

Thanks for listening (or rather reading), I'll make a code suggestion according to option 3.

**Comment by dlaehnemann** [comment]
Just to add further context for people coming here, the non-heap space memory usage of the java virtual machine (beyond what is specified by `--Xmx`), is [also an issue for Kubernetes clusters](https://akobor.me/posts/heap-size-and-resource-limits-in-kubernetes-for-jvm-applications).

And here's an article that digs deep into [heap and non-heap memory of the java virtual machine](https://betterprogramming.pub/understanding-the-jvm-memory-model-heap-vs-non-heap-c14aa6fa703e?gi=41e62e614753).

**Comment by johanneskoester** [comment]
Thanks a lot for digging into this @gbinux and @dlaehnemann. The proposed PR certainly goes into the right direction. I'll comment over there.

**Comment by dlaehnemann** [comment]
Please do! I'm not entirely sure it's the best solution, so feedback is more than welcome!

**Comment by dlaehnemann** [comment]
This is now addressed for all the Java snakemake wrappers, through PR #24 over here and https://github.com/snakemake/snakemake-wrappers/pull/1150 in the `snakemake-wrappers` repo. For `gatk GenomicsDBImport`, I set the overhead to 40% instead of the default 20%, as from what I understand from the original issue and the docs of the tool, the `TileDB` can easily use more than 30% of the allocated memory.

For anybody coming here with out of memory issues on Java snakemake wrappers, if you suspect that this is due to non-heap memory running out, you might have to increase the new `get_java_opts()` parameter `java_mem_overhead_factor` from its default of `0.2` to something higher in the respective function call in the wrapper you are having an issue with. And you might have to also increase the overall `resources: mem_mb:` value in concert with this change, to ensure enough memory remains for heap allocation.

Generally, I think this is addressed and will close this issue. But feel free to open new issues if anything still doesn't work with Java memory allocation.
